### ISSUE TITLE
Is there a particular reason for doing refreshTokenWithCompletion after successfully getting token?

### ISSUE THREAD

**Issue by eugv86** [Elrashid/nativescript-client-and-identity-server-sample#2]

**Comment by Elrashid** [comment]
You don't need to call it , but i didn't try it , please try it and give me feedback

The docs :
https://market.nativescript.org/plugins/nativescript-oauth2

**Comment by eugv86** [comment]
Ya it doesn't make sense to do it during login process.  Using it after access token is expired works as intended.
